// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedOverdraftLimit")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CreditTaxDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("CustomerAssetsHeld")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("FixedCreditTaxDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<bool>("IsAccountActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LatePaymentInterestDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("LatePaymentPenaltyDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("OverLimitFixedFeeDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("OverLimitInterestDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("RegularInterestDueInCurrentCycle")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("SelfDeclaredLimit")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<int>("UsedDaysInCurrentCycle")
                        .HasColumnType("int");

                    b.Property<decimal>("UsedOverLimit")
                        .HasColumnType("decimal(28, 10)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsAccountActive");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsContractActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LatePaymentPenaltyRate")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("MonthlyInterestRate")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("MonthlyLatePaymentInterestRate")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("MonthlyOverLimitInterestRate")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("OverLimitFixedFee")
                        .HasColumnType("decimal(28, 10)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsContractActive");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ContractAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsContractAgreementActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("SignatureDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsContractAgreementActive");

                    b.ToTable("ContractAgreements", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyLimitUsageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedOverdraftLimit")
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("UsedOverLimit")
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ReferenceDate");

                    b.ToTable("DailyLimitUsageEntries", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MonthlyChargeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedOverdraftLimit")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("CapitalizedPrincipal")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReferenceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCreditTaxDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalFixedCreditTaxDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalLatePaymentInterestDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalLatePaymentPenaltyDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalOverLimitFixedFeeDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalOverLimitInterestDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("TotalRegularInterestDue")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<int>("UsedDaysInCurrentCycle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ReferenceDate");

                    b.ToTable("MonthlyChargeSnapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ProductCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("MaxAssetsHeld")
                        .HasColumnType("decimal(28, 10)");

                    b.Property<decimal>("MinAssetsHeld")
                        .HasColumnType("decimal(28, 10)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MaxAssetsHeld");

                    b.HasIndex("MinAssetsHeld");

                    b.ToTable("ProductConditions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
